### ISSUE TITLE
博主，怎么配置使用来生成jsp项目啊？

### ISSUE THREAD

**Issue by water-1479** [kfyty/kfyty-framework#21]
博主，怎么配置使用来生成jsp项目啊？这个可以生成前后端代码吗？

**Comment by kfyty** [comment]
你好，这个项目不是像若依那样的脚手架，定位是底层框架，类似于若依中的springboot系列组件。
kfyty-database 中的代码生成器也是一个生成器框架，需要自行写模板生成代码。
感谢关注。

**Comment by kfyty** [comment]
先关闭了哈
